import Forsythe.Polynomial.Quadratic
import Forsythe.Polynomial.FourNode
import Forsythe.Polynomial.Lagrange
import Forsythe.Polynomial.MomentStability
import Forsythe.Arnoldi.Defs
import Forsythe.Arnoldi.Algebra
import Forsythe.Arnoldi.MomentGram
import Forsythe.Arnoldi.Cyclic
import Forsythe.Arnoldi.Step
import Forsythe.Arnoldi.Continuity
import Forsythe.Arnoldi.Energy
import Forsythe.Arnoldi.Foundation
import Forsythe.Arnoldi.Bounds
import Forsythe.Arnoldi.Grade
import Forsythe.Arnoldi.Orbit
import Forsythe.Arnoldi.PeriodicLimit
import Forsythe.Arnoldi.Asymptotics
import Forsythe.Arnoldi.LimitGrade
import Forsythe.Arnoldi.Coercivity
import Forsythe.Arnoldi.OrbitCoercivity
import Forsythe.Arnoldi.Variation
import Forsythe.Arnoldi.FactorConvergence
import Forsythe.Arnoldi.OrbitVariation
import Forsythe.Arnoldi.PolynomialLimits
import Forsythe.Arnoldi.Recurrence
import Forsythe.Arnoldi.OddLimit
import Forsythe.Dynamics.ClusterSet
import Forsythe.Dynamics.ClusterConvergence
import Forsythe.Dynamics.Parity
import Forsythe.Dynamics.Scalar
import Forsythe.Dynamics.ScalarClosure
import Forsythe.Dynamics.RayConvergence
import Forsythe.Exterior.LogEstimate
import Forsythe.Exterior.CubicCancellation
import Forsythe.Exterior.Cocycle
import Forsythe.Exterior.Geometric
import Forsythe.Exterior.StrictContraction
import Forsythe.Exterior.Decay
import Forsythe.Spectral.Coordinates
import Forsythe.Spectral.Grade
import Forsythe.Spectral.Stabilization
import Forsythe.Spectral.ComponentRecurrence
import Forsythe.Spectral.Moments
import Forsythe.Spectral.LimitEquation
import Forsythe.Spectral.Support
import Forsythe.Spectral.Reduction
import Forsythe.Spectral.ThreeNode
import Forsythe.Spectral.ThreeNodeConvergence
import Forsythe.Spectral.LimitOrthogonality
import Forsythe.Spectral.ThreeNodeBranch
import Forsythe.Spectral.WeightConvergence
import Forsythe.Spectral.PrincipalWeights
import Forsythe.Spectral.ExteriorMass
import Forsythe.Spectral.PrincipalPerturbation
import Forsythe.Spectral.PrincipalUpdatePerturbation
import Forsythe.Spectral.PrincipalAsymptotics
import Forsythe.Spectral.FourNodeBranch
import Forsythe.Spectral.OrderedFourNode
import Forsythe.Spectral.ExteriorDecayBranch
import Forsythe.Spectral.OrderedExteriorDecay
import Forsythe.Spectral.OrderedFourNodeClosure
import Forsythe.Spectral.FourNodeConvergence
import Forsythe.FourNode.Weights
import Forsythe.FourNode.Rho
import Forsythe.FourNode.Interpolation
import Forsythe.FourNode.Fiber
import Forsythe.FourNode.Gap
import Forsythe.FourNode.Continuity
import Forsythe.FourNode.FiberCurve
import Forsythe.FourNode.Perturbation
import Forsythe.FourNode.Closure
import Forsythe.FourNode.RemainderContinuity
import Forsythe.FourNode.EventualClosure
import Forsythe.FourNode.TailFloors
import Forsythe.FourNode.ParityAsymptotics
import Forsythe.FourNode.MiddleGapAsymptotics
import Forsythe.FourNode.CoefficientAsymptotics
import Forsythe.FourNode.MultiplierAsymptotics
import Forsythe.FourNode.AsymptoticClosure
import Forsythe.Matrix.Bridge
import Forsythe.Main
import Forsythe.Matrix.Main

/-!
# The Forsythe conjecture for restart length two

This is the import-only root of the paper-companion formalization.
-/
