import Forsythe.Spectral.Coordinates
import Mathlib.LinearAlgebra.Dimension.Constructions
import Mathlib.LinearAlgebra.Lagrange

/-!
# Grade in grouped spectral coordinates

For a self-adjoint operator, the cyclic subspace generated by `v` has one
dimension for each distinct eigenspace in which `v` has a nonzero component.
The proof uses Lagrange polynomials on the finite set of active eigenvalues;
no eigenbasis inside a repeated eigenspace is chosen.
-/

set_option autoImplicit false

namespace Forsythe
namespace Spectral

open Module.End Polynomial Set

noncomputable section

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
  [FiniteDimensional ℝ E]

omit [FiniteDimensional ℝ E] in
private theorem eigenvalue_coe_injective (A : Module.End ℝ E) :
    Function.Injective (fun mu : A.Eigenvalues ↦ (mu : ℝ)) :=
  Subtype.coe_injective

omit [FiniteDimensional ℝ E] in
/-- Polynomial action on the starting vector always belongs to its cyclic
subspace. -/
theorem polyApply_mem_cyclicSubspace (A : Module.End ℝ E)
    (p : Polynomial ℝ) (v : E) :
    polyApply A p v ∈ cyclicSubspace A v := by
  induction p using Polynomial.induction_on' with
  | add p q hp hq =>
      simpa only [polyApply, map_add, LinearMap.add_apply] using
        (cyclicSubspace A v).add_mem hp hq
  | monomial n c =>
      have hpow : (A ^ n) v ∈ cyclicSubspace A v := by
        rw [cyclicSubspace]
        exact Submodule.subset_span ⟨n, rfl⟩
      rw [polyApply, Polynomial.aeval_monomial]
      exact (cyclicSubspace A v).smul_mem c hpow

/-- The Lagrange polynomial selecting one active distinct eigenvalue, applied
to `v`. -/
def activeLagrangeVector (A : Module.End ℝ E) (hA : A.IsSymmetric)
    (v : E) (mu : ↑(active A hA v)) : E :=
  polyApply A
    (Lagrange.basis (active A hA v) (fun nu : A.Eigenvalues ↦ (nu : ℝ)) mu.1) v

/-- Active Lagrange vectors have the Kronecker-delta component property on
the active eigenspaces. -/
theorem component_activeLagrangeVector
    (A : Module.End ℝ E) (hA : A.IsSymmetric) (v : E)
    (mu nu : ↑(active A hA v)) :
    component A hA (activeLagrangeVector A hA v mu) nu.1 =
      if mu = nu then component A hA v nu.1 else 0 := by
  rw [activeLagrangeVector, component_polyApply]
  by_cases hmunu : mu = nu
  · subst nu
    rw [Lagrange.eval_basis_self
      (eigenvalue_coe_injective A).injOn mu.2, one_smul, if_pos rfl]
  · have hval :
        (Lagrange.basis (active A hA v)
          (fun xi : A.Eigenvalues ↦ (xi : ℝ)) mu.1).eval (nu.1 : ℝ) = 0 := by
      apply Lagrange.eval_basis_of_ne
      · intro hcoe
        apply hmunu
        exact Subtype.ext hcoe
      · exact nu.2
    rw [hval, zero_smul, if_neg hmunu]

/-- The active Lagrange vectors are linearly independent.  Looking at one
grouped eigenspace component isolates the corresponding coefficient. -/
theorem linearIndependent_activeLagrangeVector
    (A : Module.End ℝ E) (hA : A.IsSymmetric) (v : E) :
    LinearIndependent ℝ (activeLagrangeVector A hA v) := by
  classical
  rw [Fintype.linearIndependent_iff]
  intro c hsum mu
  have hcomponent := congrArg
    (fun x : E ↦ component A hA x mu.1) hsum
  have hsumComponent :
      component A hA
          (∑ nu, c nu • activeLagrangeVector A hA v nu) mu.1 =
        ∑ nu, c nu •
          component A hA (activeLagrangeVector A hA v nu) mu.1 := by
    simp [component]
  rw [hsumComponent] at hcomponent
  simp only [component_activeLagrangeVector] at hcomponent
  have hcoefficient : c mu • component A hA v mu.1 = 0 := by
    simpa [component] using hcomponent
  have hactive : component A hA v mu.1 ≠ 0 :=
    (mem_active_iff A hA v mu.1).mp mu.2
  exact (smul_eq_zero.mp hcoefficient).resolve_right hactive

/-- Every polynomial action is reconstructed from its values on the active
distinct eigenvalues and the active Lagrange vectors. -/
theorem polyApply_eq_sum_activeLagrangeVector
    (A : Module.End ℝ E) (hA : A.IsSymmetric)
    (p : Polynomial ℝ) (v : E) :
    polyApply A p v =
      ∑ mu : ↑(active A hA v),
        p.eval (mu.1 : ℝ) • activeLagrangeVector A hA v mu := by
  classical
  apply hA.diagonalization.injective
  ext nu
  have hcomponentGoal :
      component A hA (polyApply A p v) nu =
        component A hA
          (∑ mu : ↑(active A hA v),
            p.eval (mu.1 : ℝ) • activeLagrangeVector A hA v mu) nu := by
    rw [component_polyApply]
    have hright :
        component A hA
            (∑ mu : ↑(active A hA v),
              p.eval (mu.1 : ℝ) • activeLagrangeVector A hA v mu) nu =
          ∑ mu : ↑(active A hA v),
            p.eval (mu.1 : ℝ) •
              component A hA (activeLagrangeVector A hA v mu) nu := by
      simp [component]
    by_cases hnu : nu ∈ active A hA v
    · let nu' : ↑(active A hA v) := ⟨nu, hnu⟩
      rw [hright]
      have hcomponent (mu : ↑(active A hA v)) :
          component A hA (activeLagrangeVector A hA v mu) nu =
            if mu = nu' then component A hA v nu else 0 := by
        simpa [nu'] using component_activeLagrangeVector A hA v mu nu'
      simp_rw [hcomponent, smul_ite, smul_zero]
      simp only [Finset.sum_ite_eq', Finset.mem_univ, if_pos, nu']
    · have hzero : component A hA v nu = 0 := by
        rw [← not_ne_iff]
        exact fun hne ↦ hnu ((mem_active_iff A hA v nu).mpr hne)
      rw [hzero, smul_zero, hright]
      simp_rw [activeLagrangeVector, component_polyApply, hzero, smul_zero]
      simp
  exact congrArg Subtype.val hcomponentGoal

/-- The cyclic subspace is exactly the span of the active Lagrange vectors. -/
theorem cyclicSubspace_eq_span_activeLagrangeVector
    (A : Module.End ℝ E) (hA : A.IsSymmetric) (v : E) :
    cyclicSubspace A v =
      Submodule.span ℝ (range (activeLagrangeVector A hA v)) := by
  apply le_antisymm
  · rw [cyclicSubspace]
    apply Submodule.span_le.mpr
    rintro _ ⟨k, rfl⟩
    change (A ^ k) v ∈
      Submodule.span ℝ (range (activeLagrangeVector A hA v))
    have hpoly : polyApply A (X ^ k) v = (A ^ k) v := by
      simp [polyApply]
    rw [← hpoly, polyApply_eq_sum_activeLagrangeVector A hA]
    exact Submodule.sum_mem _ fun mu _ ↦
      (Submodule.span ℝ (range (activeLagrangeVector A hA v))).smul_mem _
        (Submodule.subset_span ⟨mu, rfl⟩)
  · apply Submodule.span_le.mpr
    rintro _ ⟨mu, rfl⟩
    exact polyApply_mem_cyclicSubspace A _ v

/-- Intrinsic grade equals the number of active distinct eigenvalues. -/
theorem grade_eq_card_active
    (A : Module.End ℝ E) (hA : A.IsSymmetric) (v : E) :
    grade A v = (active A hA v).card := by
  classical
  rw [grade, cyclicSubspace_eq_span_activeLagrangeVector A hA v,
    finrank_span_eq_card (linearIndependent_activeLagrangeVector A hA v)]
  exact Fintype.card_coe (active A hA v)

end

end Spectral
end Forsythe
