import Forsythe.Polynomial.Quadratic
import Mathlib.Algebra.Polynomial.AlgebraMap
import Mathlib.Analysis.InnerProductSpace.Basic
import Mathlib.LinearAlgebra.Dimension.Finrank

/-!
# Restart-two Arnoldi definitions

The definitions are total.  The grade hypotheses used by the convergence
theorem later show that the moment determinant and every normalization
denominator are nonzero.
-/

set_option autoImplicit false

namespace Forsythe

noncomputable section

section Algebraic

variable {E : Type*} [AddCommGroup E] [Module ℝ E]

/-- Evaluation of a scalar polynomial at an endomorphism, followed by
application to a vector. -/
def polyApply (A : Module.End ℝ E) (p : Polynomial ℝ) (v : E) : E :=
  (Polynomial.aeval A p) v

@[simp]
theorem polyApply_one (A : Module.End ℝ E) (v : E) :
    polyApply A 1 v = v := by
  simp [polyApply]

@[simp]
theorem polyApply_mul (A : Module.End ℝ E) (p q : Polynomial ℝ) (v : E) :
    polyApply A (p * q) v = polyApply A p (polyApply A q v) := by
  simp [polyApply]

@[simp]
theorem polyApply_smul (A : Module.End ℝ E) (p : Polynomial ℝ) (c : ℝ) (v : E) :
    polyApply A p (c • v) = c • polyApply A p v := by
  simp [polyApply]

/-- The cyclic subspace generated by `v` under `A`. -/
def cyclicSubspace (A : Module.End ℝ E) (v : E) : Submodule ℝ E :=
  Submodule.span ℝ (Set.range fun k : ℕ => (A ^ k) v)

end Algebraic

section InnerProduct

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]

/-- The polynomial inner product at a vector. -/
def polyInner (A : Module.End ℝ E) (v : E) (p q : Polynomial ℝ) : ℝ :=
  inner ℝ (polyApply A p v) (polyApply A q v)

/-- The `j`th scalar moment of `(A,v)`. -/
def moment (A : Module.End ℝ E) (v : E) (j : ℕ) : ℝ :=
  inner ℝ ((A ^ j) v) v

/-- Determinant of the moment Gram matrix of `1,z`. -/
def momentGramDet (A : Module.End ℝ E) (v : E) : ℝ :=
  moment A v 0 * moment A v 2 - moment A v 1 ^ 2

/-- The monic quadratic obtained by solving the two Arnoldi orthogonality
equations.  Division by zero is harmless at the definition level; valid
states later have a strictly positive determinant. -/
noncomputable def arnoldiPoly2 (A : Module.End ℝ E) (v : E) : MonicQuadratic where
  linearCoeff :=
    (moment A v 1 * moment A v 2 - moment A v 0 * moment A v 3) /
      momentGramDet A v
  constantCoeff :=
    (moment A v 1 * moment A v 3 - moment A v 2 ^ 2) /
      momentGramDet A v

/-- The unnormalized restart-two Arnoldi update. -/
noncomputable def rawArnoldiStep2 (A : Module.End ℝ E) (v : E) : E :=
  polyApply A (arnoldiPoly2 A v).toPolynomial v

/-- The normalized restart-two Arnoldi update. -/
noncomputable def arnoldiStep2 (A : Module.End ℝ E) (v : E) : E :=
  ‖rawArnoldiStep2 A v‖⁻¹ • rawArnoldiStep2 A v

/-- The restart-two Arnoldi orbit. -/
noncomputable def arnoldiOrbit2 (A : Module.End ℝ E) (v₀ : E) : ℕ → E
  | 0 => v₀
  | k + 1 => arnoldiStep2 A (arnoldiOrbit2 A v₀ k)

@[simp]
theorem arnoldiOrbit2_zero (A : Module.End ℝ E) (v₀ : E) :
    arnoldiOrbit2 A v₀ 0 = v₀ :=
  rfl

@[simp]
theorem arnoldiOrbit2_succ (A : Module.End ℝ E) (v₀ : E) (k : ℕ) :
    arnoldiOrbit2 A v₀ (k + 1) = arnoldiStep2 A (arnoldiOrbit2 A v₀ k) :=
  rfl

end InnerProduct

section Grade

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
  [FiniteDimensional ℝ E]

/-- Intrinsic grade: the dimension of the cyclic subspace. -/
noncomputable def grade (A : Module.End ℝ E) (v : E) : ℕ :=
  Module.finrank ℝ (cyclicSubspace A v)

end Grade

end

end Forsythe
